// Generated by https://quicktype.io
import 'dart:convert';

class PokemonModel {
  int? id;
  String? name;
  int? height;
  int? weight;
  Sprites? sprites;

  PokemonModel({
    this.id,
    this.name,
    this.height,
    this.weight,
    this.sprites,
  });

  factory PokemonModel.fromJson(String source) =>
      PokemonModel.fromMap(json.decode(source));

  factory PokemonModel.fromMap(Map<String, dynamic> map) {
    return PokemonModel(
      id: map['id'],
      name: map['name'],
      height: map['height'],
      weight: map['weight'],
      sprites: Sprites.fromMap(map['sprites']),
    );
  }

  String toJson() => json.encode(toMap());

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'height': height,
      'weight': weight,
      'sprites': sprites?.toMap(),
    };
  }
}

class Sprites {
  String? frontDefault;
  String? frontShiny;
  String? frontFemale;
  String? frontShinyFemale;
  String? backDefault;
  String? backShiny;
  String? backFemale;
  String? backShinyFemale;

  Sprites({
    this.frontDefault,
    this.frontShiny,
    this.frontFemale,
    this.frontShinyFemale,
    this.backDefault,
    this.backShiny,
    this.backFemale,
    this.backShinyFemale,
  });

  factory Sprites.fromJson(String source) =>
      Sprites.fromMap(json.decode(source));

  factory Sprites.fromMap(Map<String, dynamic> map) {
    return Sprites(
      frontDefault: map['front_default'],
      frontShiny: map['front_shiny'],
      frontFemale: map['front_female'],
      frontShinyFemale: map['front_shiny_female'],
      backDefault: map['back_default'],
      backShiny: map['back_shiny'],
      backFemale: map['back_female'],
      backShinyFemale: map['back_shiny_female'],
    );
  }

  String toJson() => json.encode(toMap());

  Map<String, dynamic> toMap() {
    return {
      'front_default': frontDefault,
      'front_shiny': frontShiny,
      'front_female': frontFemale,
      'front_shiny_female': frontShinyFemale,
      'back_default': backDefault,
      'back_shiny': backShiny,
      'back_female': backFemale,
      'back_shiny_female': backShinyFemale,
    };
  }
}
